/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_tiwoc_botandemo_Native */

#ifndef _Included_de_tiwoc_botandemo_Native
#define _Included_de_tiwoc_botandemo_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_tiwoc_botandemo_Native
 * Method:    pbkdf2Demo
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_tiwoc_botandemo_Native_pbkdf2Demo
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
